/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as SourceRouteImport } from './routes/source'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SuiteRouteImport } from './routes/suite'
import { Route as ApiConnectorsRouteImport } from './routes/api/connectors'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiPipelineRouteImport } from './routes/api/pipeline'
import { Route as ApiSourceRouteImport } from './routes/api/source'
import { Route as ApiAiAnalyzeRouteImport } from './routes/api/ai/analyze'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai/status'
import { Route as ApiWebhooksLinearRouteImport } from './routes/api/webhooks/linear'
import { Route as ApiWebhooksLinearReplayRouteImport } from './routes/api/webhooks/linear.replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiteRoute = SuiteRouteImport.update({
  id: '/suite',
  path: '/suite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsRoute = ApiConnectorsRouteImport.update({
  id: '/api/connectors',
  path: '/api/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelineRoute = ApiPipelineRouteImport.update({
  id: '/api/pipeline',
  path: '/api/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyzeRoute = ApiAiAnalyzeRouteImport.update({
  id: '/api/ai/analyze',
  path: '/api/ai/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksLinearRoute = ApiWebhooksLinearRouteImport.update({
  id: '/api/webhooks/linear',
  path: '/api/webhooks/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksLinearReplayRoute = ApiWebhooksLinearReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => ApiWebhooksLinearRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/batch': typeof BatchRoute
  '/generate': typeof GenerateRoute
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/score': typeof ScoreRoute
  '/source': typeof SourceRoute
  '/studio': typeof StudioRoute
  '/suite': typeof SuiteRoute
  '/api/connectors': typeof ApiConnectorsRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/pipeline': typeof ApiPipelineRoute
  '/api/source': typeof ApiSourceRoute
  '/api/ai/analyze': typeof ApiAiAnalyzeRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/webhooks/linear': typeof ApiWebhooksLinearRouteWithChildren
  '/api/webhooks/linear/replay': typeof ApiWebhooksLinearReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/batch': typeof BatchRoute
  '/generate': typeof GenerateRoute
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/score': typeof ScoreRoute
  '/source': typeof SourceRoute
  '/studio': typeof StudioRoute
  '/suite': typeof SuiteRoute
  '/api/connectors': typeof ApiConnectorsRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/pipeline': typeof ApiPipelineRoute
  '/api/source': typeof ApiSourceRoute
  '/api/ai/analyze': typeof ApiAiAnalyzeRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/webhooks/linear': typeof ApiWebhooksLinearRouteWithChildren
  '/api/webhooks/linear/replay': typeof ApiWebhooksLinearReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/batch': typeof BatchRoute
  '/generate': typeof GenerateRoute
  '/jobs': typeof JobsRoute
  '/models': typeof ModelsRoute
  '/score': typeof ScoreRoute
  '/source': typeof SourceRoute
  '/studio': typeof StudioRoute
  '/suite': typeof SuiteRoute
  '/api/connectors': typeof ApiConnectorsRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/pipeline': typeof ApiPipelineRoute
  '/api/source': typeof ApiSourceRoute
  '/api/ai/analyze': typeof ApiAiAnalyzeRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/webhooks/linear': typeof ApiWebhooksLinearRouteWithChildren
  '/api/webhooks/linear/replay': typeof ApiWebhooksLinearReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/batch'
    | '/generate'
    | '/jobs'
    | '/models'
    | '/score'
    | '/source'
    | '/studio'
    | '/suite'
    | '/api/connectors'
    | '/api/jobs'
    | '/api/models'
    | '/api/pipeline'
    | '/api/source'
    | '/api/ai/analyze'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/ai/status'
    | '/api/webhooks/linear'
    | '/api/webhooks/linear/replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/batch'
    | '/generate'
    | '/jobs'
    | '/models'
    | '/score'
    | '/source'
    | '/studio'
    | '/suite'
    | '/api/connectors'
    | '/api/jobs'
    | '/api/models'
    | '/api/pipeline'
    | '/api/source'
    | '/api/ai/analyze'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/ai/status'
    | '/api/webhooks/linear'
    | '/api/webhooks/linear/replay'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/batch'
    | '/generate'
    | '/jobs'
    | '/models'
    | '/score'
    | '/source'
    | '/studio'
    | '/suite'
    | '/api/connectors'
    | '/api/jobs'
    | '/api/models'
    | '/api/pipeline'
    | '/api/source'
    | '/api/ai/analyze'
    | '/api/ai/chat'
    | '/api/ai/generate'
    | '/api/ai/status'
    | '/api/webhooks/linear'
    | '/api/webhooks/linear/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  BatchRoute: typeof BatchRoute
  GenerateRoute: typeof GenerateRoute
  JobsRoute: typeof JobsRoute
  ModelsRoute: typeof ModelsRoute
  ScoreRoute: typeof ScoreRoute
  SourceRoute: typeof SourceRoute
  StudioRoute: typeof StudioRoute
  SuiteRoute: typeof SuiteRoute
  ApiConnectorsRoute: typeof ApiConnectorsRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPipelineRoute: typeof ApiPipelineRoute
  ApiSourceRoute: typeof ApiSourceRoute
  ApiAiAnalyzeRoute: typeof ApiAiAnalyzeRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiWebhooksLinearRoute: typeof ApiWebhooksLinearRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suite': {
      id: '/suite'
      path: '/suite'
      fullPath: '/suite'
      preLoaderRoute: typeof SuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors': {
      id: '/api/connectors'
      path: '/api/connectors'
      fullPath: '/api/connectors'
      preLoaderRoute: typeof ApiConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipeline': {
      id: '/api/pipeline'
      path: '/api/pipeline'
      fullPath: '/api/pipeline'
      preLoaderRoute: typeof ApiPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/analyze': {
      id: '/api/ai/analyze'
      path: '/api/ai/analyze'
      fullPath: '/api/ai/analyze'
      preLoaderRoute: typeof ApiAiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/linear': {
      id: '/api/webhooks/linear'
      path: '/api/webhooks/linear'
      fullPath: '/api/webhooks/linear'
      preLoaderRoute: typeof ApiWebhooksLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/linear/replay': {
      id: '/api/webhooks/linear/replay'
      path: '/replay'
      fullPath: '/api/webhooks/linear/replay'
      preLoaderRoute: typeof ApiWebhooksLinearReplayRouteImport
      parentRoute: typeof ApiWebhooksLinearRoute
    }
  }
}

interface ApiWebhooksLinearRouteChildren {
  ApiWebhooksLinearReplayRoute: typeof ApiWebhooksLinearReplayRoute
}

const ApiWebhooksLinearRouteChildren: ApiWebhooksLinearRouteChildren = {
  ApiWebhooksLinearReplayRoute: ApiWebhooksLinearReplayRoute,
}

const ApiWebhooksLinearRouteWithChildren =
  ApiWebhooksLinearRoute._addFileChildren(ApiWebhooksLinearRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  BatchRoute: BatchRoute,
  GenerateRoute: GenerateRoute,
  JobsRoute: JobsRoute,
  ModelsRoute: ModelsRoute,
  ScoreRoute: ScoreRoute,
  SourceRoute: SourceRoute,
  StudioRoute: StudioRoute,
  SuiteRoute: SuiteRoute,
  ApiConnectorsRoute: ApiConnectorsRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiPipelineRoute: ApiPipelineRoute,
  ApiSourceRoute: ApiSourceRoute,
  ApiAiAnalyzeRoute: ApiAiAnalyzeRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiWebhooksLinearRoute: ApiWebhooksLinearRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
